id: P3B39F2EC
initial_creation_type: input
source_metadata:
  title: Jigme Lingpa Series
  language: zh
  description: A series of texts by and about the great Dzogchen master Rigdzin Jigme
    Lingpa (rig 'dzin 'jigs med gling pa, 1730–1798), who revealed the Longchen Nyingtik
    (klong chen snying thig) collection.
  volume:
    534938890dfa4e8596b8d76e6221f4f4:
      title: An Aspiration for the Final Age
      parent: Aspiration Prayers
    b002cf5408a54f1da4279d0db51dce48:
      title: Aspiration to Be Reborn in the Realm of Sukhāvatī
      parent: Aspiration Prayers
    3cfd9741f1e94bc9b6350fa7d33d7c32:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: Aspiration Prayers
    1b99a33f6acc46319b0ee534ffe24b1e:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Aspiration Prayers
    d5162a3b3b2e45beb2a58f44dd15d00c:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Aspiration Prayers
    a7dbc0a026a74777850a24780f98de3a:
      title: 'Precise Discernment of Dharmas: A Catalogue of the Complete Collected
        Works of the Omniscient King of Dharma, Rigdzin Jigme Lingpa'
      parent: Catalogues
    fce958e7e1194694b2da1ced4ed84404:
      title: 'Elucidating the Body Maṇḍala: Clarifications on the Recitation Manual
        of the Female Practice of the Queen of Great Bliss'
      parent: Commentaries
    80ec0a2233994fa29ffdf5aff149d52c:
      title: Main Recitation Manual for the Female Practice of the Queen of Great
        Bliss
      parent: Commentaries
    4df6b8f102d143baae7129cfc090761c:
      title: 'The Casket of Siddhis: A Recitation Manual for “Vidyādhara Assembly”
        (Rigdzin Düpa)'
      parent: Commentaries
    595c4a5ac6cb4cdf8b059e6a90f87f87:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Commentaries
    0a55a7b8c38449a0be5d95271842830a:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Commentaries
    7345ec5e007545a480645825ecc61140:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Confession
    bc8e87f1b9fe48cdb5d1b73806f4b77f:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Dharma Protectors
    9dacb7b5af574463b252783c878c5b4c:
      title: Vajra Verses on the Natural State
      parent: Dzogchen
    bffcb253970742e58d166c0c378513b1:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Empowerment Rites
    1adbd9a85616457fabb3ce94e9122ab7:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Empowerment Rites
    ddf01163aee64c159fc420cd4d59b207:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Empowerment Rites
    d198606429ac4fd5a2b52cbefbae8eeb:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Guru Rinpoche Prayers
    4e56284f106747b1818cb0e45e6b3988:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Guru Rinpoche Prayers
    c61b64b2dec3460894507f70f16fb783:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Guru Rinpoche Prayers
    cc574402a3f04fd7a6998e983f6c3ded:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    610631f348b541358c2d84194683b202:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Guru Rinpoche Prayers
    638a370d02a848febff5929bd4a0d4c2:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Guru Yoga
    33f87df703394acb9c521be1a80046f8:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Guru Yoga
    72ef2f459c91409aba861af3ba8a2661:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: History
    a1d3d07f58754dadadb81d1efbddb50b:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    a5c1d38c294a4922a0cf3a5610bf5d5a:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Lineage Prayers
    3ed2ff0128714709916ab9b89018e721:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Longchen Nyingtik
    46902eeebae947dcbddacac6f0afc33a:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    960e6269e7b743e7ac8c43a83bf431e2:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Pilgrimage
    5259ecb8fb51426f99dfbc650a14a505:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    84be6f03628247138152fa279980904c:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Practices
    c9d01b848f9f4a93ae5829e3492a34b0:
      title: Descent of Blessings of the Eight Vidyādharas
      parent: Practices
    8314055088c645f5a8cdf1c2b910ee64:
      title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
      parent: Practices
    bfb34363bce14a0f906b3c7eba300645:
      title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female
        Awareness-Holder (Yumka)'
      parent: Practices
    5b625abc7d1b4fa5bd531ad2f9170941:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      parent: Practices
    cd7f73bb03c3499c9ff94d6b8376fabb:
      title: The Eight-Branch Offering from the Gyüluk Phurba
      parent: Practices
    89a704f809ec4da4a3ecb642c456d05b:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Practices
    3e8ca514fecc4604b9335c1d2f6d40aa:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Practices
    095e14f4a4044a729e30070452747366:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Praise
    28645c7d1fbb4578bfad7bcaaf818aeb:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Praise
    024c3bcf68064cd094e34c6e1794ecc7:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    c8ce01bd6f7b4dbc811ed084b6548d79:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Prayers
    906db5cb330d47ef8ad423c798738240:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Prayers
    f293189271cf42e88650da96d572e83b:
      title: 'Devotion that Pierces the Heart: A Prayer to the Omniscient Jigme Lingpa'
      parent: Prayers
    9f1852075d3743de86662bf9c96c745a:
      title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
      parent: Prayers
    341d755dac5441f69d4371422b14311f:
      title: Prayer to the Garland of Rebirths of the Dzogchenpas of Eastern Tibet
      parent: Prayers
    d55550c67a554da0be75f5f23327ecd3:
      title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
      parent: Prayers
    66c556fdb4544a1885214a98f3878269:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Prayers
    e93cf1ca8fd24f4aa851659594fec6b0:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Sādhanas
    1a63c4d08d3a40c28e4fe6751ad83cdf:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    a464d63ab1b3487093a2554670f08183:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Sādhanas
    7402bf9445ec465396fa5c07d917fd78:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Sādhanas
    2964a2cd8a2d4569bd5f978ef718fe65:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Sādhanas
    7e2511cf1fb54dda83e89490adae4d1a:
      title: Sādhana of the Great Master Vairotsana
      parent: Sādhanas
    b17b025525804f45b95ebca6fd5536b6:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Sādhanas
    35417fc466b34761bd2b37f63e17c3a5:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Sādhanas
    fc75fde13a7e4655a6758c36e29336c9:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Transference (Phowa)
    5a4b4df061e240e9a2eede4537ad2e82:
      title: Brief Prayer of the Feast Gathering
      parent: Tsok
    e869385d798a46fbab98d374d884bd11:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Tsok
    0d097db7555c453dbeb8fc767b9137d4:
      title: Song of the Feast (Tsok Lu)
      parent: Tsok
    0c46cb982a1349e999f66cb72fe0c113:
      title: 'Calling the Guru from Afar: A Prayer to Jigme Lingpa'
      parent: Calling the Guru from Afar
created_at: '2022-03-01T00:07:12.494911'
last_modified_at: '2022-03-01T00:07:12.494914'
